-- Portal Controladoria — migração inicial
-- Cole este SQL no editor do Supabase: https://supabase.com/dashboard/project/ocwzukuzumewtbxiibzw/sql

CREATE TABLE IF NOT EXISTS natureza (
  id TEXT PRIMARY KEY,
  "CODNAT" TEXT NOT NULL DEFAULT '',
  "DESCRNAT" TEXT NOT NULL DEFAULT '',
  "GRAU" INTEGER NOT NULL DEFAULT 1,
  "ANALITICA" BOOLEAN NOT NULL DEFAULT true,
  "ATIVA" BOOLEAN NOT NULL DEFAULT true,
  "TIPO_REGISTRO" TEXT NOT NULL DEFAULT 'GERENCIAL',
  "ENTRA_RESULTADO" TEXT NOT NULL DEFAULT 'DRE',
  "CLASSIFICACAO" TEXT NOT NULL DEFAULT '',
  "PACOTES" TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS centro_resultado (
  id TEXT PRIMARY KEY,
  "CODCENCUS" TEXT NOT NULL DEFAULT '',
  "DESCRCENCUS" TEXT NOT NULL DEFAULT '',
  "ATIVO" BOOLEAN NOT NULL DEFAULT true,
  "GRAU" INTEGER NOT NULL DEFAULT 1,
  "ANALITICO" BOOLEAN NOT NULL DEFAULT true,
  "TIPO_REGISTRO" TEXT NOT NULL DEFAULT 'GERENCIAL',
  "ENTRA_RESULTADO" TEXT NOT NULL DEFAULT 'DRE',
  "CLASSIFICACAO" TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS projetos (
  id TEXT PRIMARY KEY,
  "CODPROJ" TEXT NOT NULL DEFAULT '',
  "IDENTIFICACAO" TEXT NOT NULL DEFAULT '',
  "ATIVO" BOOLEAN NOT NULL DEFAULT true,
  "GRAU" INTEGER NOT NULL DEFAULT 1,
  "ANALITICO" BOOLEAN NOT NULL DEFAULT true,
  "TIPO_REGISTRO" TEXT NOT NULL DEFAULT 'GERENCIAL'
);

CREATE TABLE IF NOT EXISTS parceiros (
  id TEXT PRIMARY KEY,
  "CODPARC" TEXT NOT NULL DEFAULT '',
  "NOMEPARC" TEXT NOT NULL DEFAULT '',
  "TIPO_REGISTRO" TEXT NOT NULL DEFAULT 'GERENCIAL'
);

CREATE TABLE IF NOT EXISTS empresas (
  id TEXT PRIMARY KEY,
  "CODEMP" TEXT NOT NULL DEFAULT '',
  "RAZAOSOCIAL" TEXT NOT NULL DEFAULT '',
  "TIPO_REGISTRO" TEXT NOT NULL DEFAULT 'GERENCIAL',
  "ENTRA_RESULTADO" TEXT NOT NULL DEFAULT 'DRE',
  "AD_EMPCLASS" TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS adquiridas (
  id TEXT PRIMARY KEY,
  "EMPRESA" TEXT NOT NULL DEFAULT '',
  "DATA" TEXT NOT NULL DEFAULT '',
  "ESTADO_ORIGEM" TEXT NOT NULL DEFAULT '',
  "AREA_NEGOCIO" TEXT NOT NULL DEFAULT ''
);

-- indicadores: estrutura aninhada complexa → armazenada como JSONB
CREATE TABLE IF NOT EXISTS indicadores (
  id TEXT PRIMARY KEY,
  data JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS fechamentos (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL DEFAULT '',
  "mesReferencia" TEXT NOT NULL DEFAULT '',
  tipo TEXT NOT NULL DEFAULT 'realizado',
  ativo BOOLEAN NOT NULL DEFAULT false,
  "criadoEm" TEXT NOT NULL DEFAULT '',
  "totalLinhas" INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS lancamentos_financeiro (
  id TEXT PRIMARY KEY,
  "fechamentoId" TEXT,
  tipo TEXT NOT NULL DEFAULT 'realizado',
  data TEXT NOT NULL DEFAULT '',
  periodo TEXT NOT NULL DEFAULT '',
  codnat TEXT NOT NULL DEFAULT '',
  codcencus TEXT NOT NULL DEFAULT '',
  codemp TEXT NOT NULL DEFAULT '',
  codproj TEXT,
  codparc TEXT,
  nufin TEXT,
  historico TEXT,
  valor NUMERIC NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS lancamentos_indicadores (
  id TEXT PRIMARY KEY,
  "importacaoId" TEXT,
  tipo TEXT NOT NULL DEFAULT 'realizado',
  data TEXT NOT NULL DEFAULT '',
  periodo TEXT NOT NULL DEFAULT '',
  cod_indicador TEXT NOT NULL DEFAULT '',
  unidade TEXT NOT NULL DEFAULT 'valor',
  valor NUMERIC NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS importacoes_indicadores (
  id TEXT PRIMARY KEY,
  tipo TEXT NOT NULL DEFAULT 'realizado',
  periodo TEXT NOT NULL DEFAULT '',
  "criadoEm" TEXT NOT NULL DEFAULT '',
  "totalLinhas" INTEGER NOT NULL DEFAULT 0
);
